// Brazilian States
export interface BrazilianState {
  code: string;
  name: string;
  capital: string;
}

export const brazilianStates: BrazilianState[] = [
  { code: 'AC', name: 'Acre', capital: 'Rio Branco' },
  { code: 'AL', name: 'Alagoas', capital: 'Maceió' },
  { code: 'AP', name: 'Amapá', capital: 'Macapá' },
  { code: 'AM', name: 'Amazonas', capital: 'Manaus' },
  { code: 'BA', name: 'Bahia', capital: 'Salvador' },
  { code: 'CE', name: 'Ceará', capital: 'Fortaleza' },
  { code: 'DF', name: 'Distrito Federal', capital: 'Brasília' },
  { code: 'ES', name: 'Espírito Santo', capital: 'Vitória' },
  { code: 'GO', name: 'Goiás', capital: 'Goiânia' },
  { code: 'MA', name: 'Maranhão', capital: 'São Luís' },
  { code: 'MT', name: 'Mato Grosso', capital: 'Cuiabá' },
  { code: 'MS', name: 'Mato Grosso do Sul', capital: 'Campo Grande' },
  { code: 'MG', name: 'Minas Gerais', capital: 'Belo Horizonte' },
  { code: 'PA', name: 'Pará', capital: 'Belém' },
  { code: 'PB', name: 'Paraíba', capital: 'João Pessoa' },
  { code: 'PR', name: 'Paraná', capital: 'Curitiba' },
  { code: 'PE', name: 'Pernambuco', capital: 'Recife' },
  { code: 'PI', name: 'Piauí', capital: 'Teresina' },
  { code: 'RJ', name: 'Rio de Janeiro', capital: 'Rio de Janeiro' },
  { code: 'RN', name: 'Rio Grande do Norte', capital: 'Natal' },
  { code: 'RS', name: 'Rio Grande do Sul', capital: 'Porto Alegre' },
  { code: 'RO', name: 'Rondônia', capital: 'Porto Velho' },
  { code: 'RR', name: 'Roraima', capital: 'Boa Vista' },
  { code: 'SC', name: 'Santa Catarina', capital: 'Florianópolis' },
  { code: 'SP', name: 'São Paulo', capital: 'São Paulo' },
  { code: 'SE', name: 'Sergipe', capital: 'Aracaju' },
  { code: 'TO', name: 'Tocantins', capital: 'Palmas' },
];

// Common cities by state (focusing on RJ since the school is there)
export const citiesByState: Record<string, string[]> = {
  RJ: [
    'Rio de Janeiro',
    'Niterói',
    'São Gonçalo',
    'Duque de Caxias',
    'Nova Iguaçu',
    'Petrópolis',
    'Volta Redonda',
    'Campos dos Goytacazes',
    'Macaé',
    'Cabo Frio',
    'Angra dos Reis',
    'Teresópolis',
    'Búzios',
    'Barra Mansa',
    'Resende',
    'Nova Friburgo',
    'Itaboraí',
    'Magé',
    'Belford Roxo',
    'São João de Meriti',
    'Nilópolis',
    'Mesquita',
    'Queimados',
    'Itaguaí',
    'Seropédica',
    'Maricá',
    'Araruama',
    'Saquarema',
    'Rio Bonito',
    'Paraty',
    'Barra do Piraí',
    'Três Rios',
    'Valença',
    'Vassouras',
    'Miguel Pereira',
    'Paty do Alferes',
    'Guapimirim',
    'Cachoeiras de Macacu',
  ],
  SP: [
    'São Paulo',
    'Guarulhos',
    'Campinas',
    'São Bernardo do Campo',
    'Santo André',
    'São José dos Campos',
    'Osasco',
    'Ribeirão Preto',
    'Sorocaba',
    'Santos',
    'Mauá',
    'São José do Rio Preto',
    'Mogi das Cruzes',
    'Diadema',
    'Jundiaí',
    'Piracicaba',
    'Carapicuíba',
    'Bauru',
    'Itaquaquecetuba',
    'São Vicente',
  ],
  MG: [
    'Belo Horizonte',
    'Uberlândia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Montes Claros',
    'Ribeirão das Neves',
    'Uberaba',
    'Governador Valadares',
    'Ipatinga',
    'Sete Lagoas',
    'Divinópolis',
    'Santa Luzia',
    'Ibirité',
    'Poços de Caldas',
    'Patos de Minas',
    'Pouso Alegre',
    'Teófilo Otoni',
    'Barbacena',
    'Sabará',
  ],
  RS: [
    'Porto Alegre',
    'Caxias do Sul',
    'Pelotas',
    'Canoas',
    'Santa Maria',
    'Gravataí',
    'Viamão',
    'Novo Hamburgo',
    'São Leopoldo',
    'Rio Grande',
    'Alvorada',
    'Passo Fundo',
    'Sapucaia do Sul',
    'Uruguaiana',
    'Cachoeirinha',
    'Santa Cruz do Sul',
    'Bagé',
    'Bento Gonçalves',
    'Erechim',
    'Guaíba',
  ],
  PR: [
    'Curitiba',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'São José dos Pinhais',
    'Foz do Iguaçu',
    'Colombo',
    'Guarapuava',
    'Paranaguá',
    'Araucária',
    'Toledo',
    'Apucarana',
    'Pinhais',
    'Campo Largo',
    'Arapongas',
    'Almirante Tamandaré',
    'Umuarama',
    'Piraquara',
    'Cambé',
  ],
  SC: [
    'Joinville',
    'Florianópolis',
    'Blumenau',
    'São José',
    'Criciúma',
    'Chapecó',
    'Itajaí',
    'Lages',
    'Jaraguá do Sul',
    'Palhoça',
    'Balneário Camboriú',
    'Brusque',
    'Tubarão',
    'São Bento do Sul',
    'Caçador',
    'Concórdia',
    'Navegantes',
    'Rio do Sul',
    'Araranguá',
    'Gaspar',
  ],
  BA: [
    'Salvador',
    'Feira de Santana',
    'Vitória da Conquista',
    'Camaçari',
    'Itabuna',
    'Juazeiro',
    'Lauro de Freitas',
    'Ilhéus',
    'Jequié',
    'Teixeira de Freitas',
    'Alagoinhas',
    'Barreiras',
    'Porto Seguro',
    'Simões Filho',
    'Paulo Afonso',
    'Eunápolis',
    'Santo Antônio de Jesus',
    'Valença',
    'Candeias',
    'Guanambi',
  ],
  PE: [
    'Recife',
    'Jaboatão dos Guararapes',
    'Olinda',
    'Caruaru',
    'Petrolina',
    'Paulista',
    'Cabo de Santo Agostinho',
    'Camaragibe',
    'Garanhuns',
    'Vitória de Santo Antão',
    'Igarassu',
    'São Lourenço da Mata',
    'Abreu e Lima',
    'Santa Cruz do Capibaribe',
    'Ipojuca',
    'Serra Talhada',
    'Araripina',
    'Gravatá',
    'Carpina',
    'Goiana',
  ],
  CE: [
    'Fortaleza',
    'Caucaia',
    'Juazeiro do Norte',
    'Maracanaú',
    'Sobral',
    'Crato',
    'Itapipoca',
    'Maranguape',
    'Iguatu',
    'Quixadá',
    'Pacatuba',
    'Quixeramobim',
    'Aquiraz',
    'Canindé',
    'Russas',
    'Tianguá',
    'Crateús',
    'Pacajus',
    'Horizonte',
    'Aracati',
  ],
  DF: ['Brasília'],
  GO: [
    'Goiânia',
    'Aparecida de Goiânia',
    'Anápolis',
    'Rio Verde',
    'Luziânia',
    'Águas Lindas de Goiás',
    'Valparaíso de Goiás',
    'Trindade',
    'Formosa',
    'Novo Gama',
    'Senador Canedo',
    'Catalão',
    'Itumbiara',
    'Jataí',
    'Planaltina',
    'Caldas Novas',
    'Santo Antônio do Descoberto',
    'Cidade Ocidental',
    'Inhumas',
    'Goianésia',
  ],
  ES: [
    'Vitória',
    'Vila Velha',
    'Serra',
    'Cariacica',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'São Mateus',
    'Colatina',
    'Guarapari',
    'Aracruz',
    'Viana',
    'Nova Venécia',
    'Barra de São Francisco',
    'Santa Maria de Jetibá',
    'Fundão',
    'Domingos Martins',
    'Afonso Cláudio',
    'Marataízes',
    'Itapemirim',
    'Piúma',
  ],
};

// Common neighborhoods for Rio de Janeiro (most common for the school)
export const neighborhoodsByCity: Record<string, string[]> = {
  'Rio de Janeiro': [
    'Copacabana',
    'Ipanema',
    'Leblon',
    'Botafogo',
    'Flamengo',
    'Laranjeiras',
    'Cosme Velho',
    'Humaitá',
    'Lagoa',
    'Jardim Botânico',
    'Gávea',
    'São Conrado',
    'Barra da Tijuca',
    'Recreio dos Bandeirantes',
    'Tijuca',
    'Grajaú',
    'Vila Isabel',
    'Maracanã',
    'Andaraí',
    'Méier',
    'Cachambi',
    'Todos os Santos',
    'Engenho Novo',
    'Jacarepaguá',
    'Taquara',
    'Freguesia',
    'Pechincha',
    'Tanque',
    'Anil',
    'Curicica',
    'Centro',
    'Glória',
    'Catete',
    'Santa Teresa',
    'Lapa',
    'Urca',
    'Leme',
    'Vidigal',
    'Rocinha',
    'Alto da Boa Vista',
    'Joá',
    'Itanhangá',
    'Vargem Grande',
    'Vargem Pequena',
    'Camorim',
    'Gardênia Azul',
    'Cidade de Deus',
    'Rio Comprido',
    'Estácio',
    'Praça da Bandeira',
    'São Cristóvão',
    'Benfica',
    'Mangueira',
    'Madureira',
    'Cascadura',
    'Piedade',
    'Quintino',
    'Abolição',
    'Pilares',
    'Del Castilho',
    'Inhaúma',
    'Higienópolis',
    'Maria da Graça',
    'Riachuelo',
    'Sampaio',
    'Rocha',
    'Bonsucesso',
    'Olaria',
    'Ramos',
    'Penha',
    'Penha Circular',
    'Brás de Pina',
    'Cordovil',
    'Parada de Lucas',
    'Vigário Geral',
    'Jardim América',
    'Vicente de Carvalho',
    'Vila da Penha',
    'Vista Alegre',
    'Irajá',
    'Colégio',
    'Campinho',
    'Cavalcanti',
    'Engenheiro Leal',
    'Turiaçu',
    'Rocha Miranda',
    'Vaz Lobo',
    'Coelho Neto',
    'Acari',
    'Barros Filho',
    'Costa Barros',
    'Pavuna',
    'Realengo',
    'Padre Miguel',
    'Bangu',
    'Senador Camará',
    'Santíssimo',
    'Campo Grande',
    'Cosmos',
    'Inhoaíba',
    'Paciência',
    'Santa Cruz',
    'Sepetiba',
    'Pedra de Guaratiba',
    'Guaratiba',
    'Barra de Guaratiba',
    'Ilha do Governador',
    'Portuguesa',
    'Bancários',
    'Cacuia',
    'Cocotá',
    'Galeão',
    'Jardim Carioca',
    'Jardim Guanabara',
    'Moneró',
    'Pitangueiras',
    'Praia da Bandeira',
    'Ribeira',
    'Tauá',
    'Zumbi',
  ],
  Niterói: [
    'Icaraí',
    'Santa Rosa',
    'São Francisco',
    'Charitas',
    'Jurujuba',
    'Ingá',
    'Boa Viagem',
    'Gragoatá',
    'Centro',
    'Ponta d\'Areia',
    'São Domingos',
    'Vital Brasil',
    'Fonseca',
    'Barreto',
    'Engenhoca',
    'Santa Bárbara',
    'Largo da Batalha',
    'Pendotiba',
    'Maria Paula',
    'Badu',
    'Itaipu',
    'Piratininga',
    'Camboinhas',
    'Itacoatiara',
    'Engenho do Mato',
    'Serra Grande',
    'Várzea das Moças',
    'Maceió',
    'Cafubá',
    'Jardim Imbuí',
  ],
  Petrópolis: [
    'Centro',
    'Quitandinha',
    'Valparaíso',
    'Alto da Serra',
    'Bingen',
    'Castelânea',
    'Corrêas',
    'Itaipava',
    'Araras',
    'Nogueira',
    'Retiro',
    'Mosela',
    'Castelanea',
    'Duarte da Silveira',
    'Quarteirão Brasileiro',
    'Quarteirão Ingelhein',
    'Independência',
    'Caxambu',
    'Siméria',
    'Samambaia',
  ],
  Teresópolis: [
    'Centro',
    'Alto',
    'Várzea',
    'Araras',
    'Bom Retiro',
    'Agriões',
    'Soberbo',
    'Granja Guarani',
    'Ermitage',
    'Tijuca',
    'Golfe',
    'Pimenteiras',
    'Albuquerque',
    'Fonte Santa',
    'Vieira',
    'Barra do Imbuí',
    'Fazendinha',
    'São Pedro',
    'Fischer',
    'Meudon',
  ],
};

// Helper to get cities for a state
export function getCitiesForState(stateCode: string): string[] {
  return citiesByState[stateCode] || [];
}

// Helper to get neighborhoods for a city
export function getNeighborhoodsForCity(cityName: string): string[] {
  return neighborhoodsByCity[cityName] || [];
}

// Helper to get state name by code
export function getStateName(stateCode: string): string {
  const state = brazilianStates.find((s) => s.code === stateCode);
  return state?.name || stateCode;
}
