export const countries = [
  { code: 'BR', en: 'Brazil', pt: 'Brasil' },
  { code: 'US', en: 'United States', pt: 'Estados Unidos' },
  { code: 'GB', en: 'United Kingdom', pt: 'Reino Unido' },
  { code: 'CA', en: 'Canada', pt: 'Canadá' },
  { code: 'AR', en: 'Argentina', pt: 'Argentina' },
  { code: 'CL', en: 'Chile', pt: 'Chile' },
  { code: 'CO', en: 'Colombia', pt: 'Colômbia' },
  { code: 'MX', en: 'Mexico', pt: 'México' },
  { code: 'PE', en: 'Peru', pt: 'Peru' },
  { code: 'UY', en: 'Uruguay', pt: 'Uruguai' },
  { code: 'VE', en: 'Venezuela', pt: 'Venezuela' },
  { code: 'PY', en: 'Paraguay', pt: 'Paraguai' },
  { code: 'BO', en: 'Bolivia', pt: 'Bolívia' },
  { code: 'EC', en: 'Ecuador', pt: 'Equador' },
  { code: 'PT', en: 'Portugal', pt: 'Portugal' },
  { code: 'ES', en: 'Spain', pt: 'Espanha' },
  { code: 'FR', en: 'France', pt: 'França' },
  { code: 'DE', en: 'Germany', pt: 'Alemanha' },
  { code: 'IT', en: 'Italy', pt: 'Itália' },
  { code: 'NL', en: 'Netherlands', pt: 'Holanda' },
  { code: 'BE', en: 'Belgium', pt: 'Bélgica' },
  { code: 'CH', en: 'Switzerland', pt: 'Suíça' },
  { code: 'AT', en: 'Austria', pt: 'Áustria' },
  { code: 'SE', en: 'Sweden', pt: 'Suécia' },
  { code: 'NO', en: 'Norway', pt: 'Noruega' },
  { code: 'DK', en: 'Denmark', pt: 'Dinamarca' },
  { code: 'FI', en: 'Finland', pt: 'Finlândia' },
  { code: 'IE', en: 'Ireland', pt: 'Irlanda' },
  { code: 'PL', en: 'Poland', pt: 'Polônia' },
  { code: 'CZ', en: 'Czech Republic', pt: 'República Tcheca' },
  { code: 'GR', en: 'Greece', pt: 'Grécia' },
  { code: 'RU', en: 'Russia', pt: 'Rússia' },
  { code: 'CN', en: 'China', pt: 'China' },
  { code: 'JP', en: 'Japan', pt: 'Japão' },
  { code: 'KR', en: 'South Korea', pt: 'Coreia do Sul' },
  { code: 'IN', en: 'India', pt: 'Índia' },
  { code: 'AU', en: 'Australia', pt: 'Austrália' },
  { code: 'NZ', en: 'New Zealand', pt: 'Nova Zelândia' },
  { code: 'ZA', en: 'South Africa', pt: 'África do Sul' },
  { code: 'IL', en: 'Israel', pt: 'Israel' },
  { code: 'AE', en: 'United Arab Emirates', pt: 'Emirados Árabes Unidos' },
  { code: 'SA', en: 'Saudi Arabia', pt: 'Arábia Saudita' },
  { code: 'EG', en: 'Egypt', pt: 'Egito' },
  { code: 'TR', en: 'Turkey', pt: 'Turquia' },
  { code: 'SG', en: 'Singapore', pt: 'Singapura' },
  { code: 'TH', en: 'Thailand', pt: 'Tailândia' },
  { code: 'MY', en: 'Malaysia', pt: 'Malásia' },
  { code: 'ID', en: 'Indonesia', pt: 'Indonésia' },
  { code: 'PH', en: 'Philippines', pt: 'Filipinas' },
  { code: 'VN', en: 'Vietnam', pt: 'Vietnã' },
];

export type Country = (typeof countries)[number];

// Cities by country code - focusing on most common countries for international schools
export const citiesByCountry: Record<string, { en: string; pt: string }[]> = {
  BR: [
    { en: 'Rio de Janeiro', pt: 'Rio de Janeiro' },
    { en: 'São Paulo', pt: 'São Paulo' },
    { en: 'Brasília', pt: 'Brasília' },
    { en: 'Belo Horizonte', pt: 'Belo Horizonte' },
    { en: 'Salvador', pt: 'Salvador' },
    { en: 'Fortaleza', pt: 'Fortaleza' },
    { en: 'Curitiba', pt: 'Curitiba' },
    { en: 'Recife', pt: 'Recife' },
    { en: 'Porto Alegre', pt: 'Porto Alegre' },
    { en: 'Manaus', pt: 'Manaus' },
    { en: 'Belém', pt: 'Belém' },
    { en: 'Goiânia', pt: 'Goiânia' },
    { en: 'Campinas', pt: 'Campinas' },
    { en: 'Guarulhos', pt: 'Guarulhos' },
    { en: 'São Gonçalo', pt: 'São Gonçalo' },
    { en: 'Niterói', pt: 'Niterói' },
    { en: 'Duque de Caxias', pt: 'Duque de Caxias' },
    { en: 'Petrópolis', pt: 'Petrópolis' },
    { en: 'Nova Iguaçu', pt: 'Nova Iguaçu' },
    { en: 'Teresópolis', pt: 'Teresópolis' },
    { en: 'Búzios', pt: 'Búzios' },
    { en: 'Cabo Frio', pt: 'Cabo Frio' },
    { en: 'Angra dos Reis', pt: 'Angra dos Reis' },
    { en: 'Volta Redonda', pt: 'Volta Redonda' },
    { en: 'Campos dos Goytacazes', pt: 'Campos dos Goytacazes' },
    { en: 'Macaé', pt: 'Macaé' },
    { en: 'Florianópolis', pt: 'Florianópolis' },
    { en: 'Vitória', pt: 'Vitória' },
    { en: 'Natal', pt: 'Natal' },
    { en: 'João Pessoa', pt: 'João Pessoa' },
    { en: 'Maceió', pt: 'Maceió' },
    { en: 'Aracaju', pt: 'Aracaju' },
    { en: 'São Luís', pt: 'São Luís' },
    { en: 'Teresina', pt: 'Teresina' },
    { en: 'Campo Grande', pt: 'Campo Grande' },
    { en: 'Cuiabá', pt: 'Cuiabá' },
    { en: 'Santos', pt: 'Santos' },
    { en: 'Ribeirão Preto', pt: 'Ribeirão Preto' },
    { en: 'Sorocaba', pt: 'Sorocaba' },
    { en: 'São José dos Campos', pt: 'São José dos Campos' },
    { en: 'Osasco', pt: 'Osasco' },
    { en: 'Santo André', pt: 'Santo André' },
    { en: 'São Bernardo do Campo', pt: 'São Bernardo do Campo' },
    { en: 'Londrina', pt: 'Londrina' },
    { en: 'Maringá', pt: 'Maringá' },
    { en: 'Joinville', pt: 'Joinville' },
    { en: 'Blumenau', pt: 'Blumenau' },
    { en: 'Uberlândia', pt: 'Uberlândia' },
    { en: 'Contagem', pt: 'Contagem' },
    { en: 'Juiz de Fora', pt: 'Juiz de Fora' },
  ],
  US: [
    { en: 'New York', pt: 'Nova York' },
    { en: 'Los Angeles', pt: 'Los Angeles' },
    { en: 'Chicago', pt: 'Chicago' },
    { en: 'Houston', pt: 'Houston' },
    { en: 'Phoenix', pt: 'Phoenix' },
    { en: 'Philadelphia', pt: 'Filadélfia' },
    { en: 'San Antonio', pt: 'San Antonio' },
    { en: 'San Diego', pt: 'San Diego' },
    { en: 'Dallas', pt: 'Dallas' },
    { en: 'San Jose', pt: 'San Jose' },
    { en: 'Austin', pt: 'Austin' },
    { en: 'Jacksonville', pt: 'Jacksonville' },
    { en: 'Fort Worth', pt: 'Fort Worth' },
    { en: 'Columbus', pt: 'Columbus' },
    { en: 'Charlotte', pt: 'Charlotte' },
    { en: 'San Francisco', pt: 'São Francisco' },
    { en: 'Indianapolis', pt: 'Indianápolis' },
    { en: 'Seattle', pt: 'Seattle' },
    { en: 'Denver', pt: 'Denver' },
    { en: 'Washington', pt: 'Washington' },
    { en: 'Boston', pt: 'Boston' },
    { en: 'Miami', pt: 'Miami' },
    { en: 'Atlanta', pt: 'Atlanta' },
    { en: 'Orlando', pt: 'Orlando' },
    { en: 'Las Vegas', pt: 'Las Vegas' },
  ],
  GB: [
    { en: 'London', pt: 'Londres' },
    { en: 'Birmingham', pt: 'Birmingham' },
    { en: 'Manchester', pt: 'Manchester' },
    { en: 'Glasgow', pt: 'Glasgow' },
    { en: 'Liverpool', pt: 'Liverpool' },
    { en: 'Bristol', pt: 'Bristol' },
    { en: 'Edinburgh', pt: 'Edimburgo' },
    { en: 'Leeds', pt: 'Leeds' },
    { en: 'Sheffield', pt: 'Sheffield' },
    { en: 'Newcastle', pt: 'Newcastle' },
    { en: 'Cambridge', pt: 'Cambridge' },
    { en: 'Oxford', pt: 'Oxford' },
  ],
  CA: [
    { en: 'Toronto', pt: 'Toronto' },
    { en: 'Montreal', pt: 'Montreal' },
    { en: 'Vancouver', pt: 'Vancouver' },
    { en: 'Calgary', pt: 'Calgary' },
    { en: 'Edmonton', pt: 'Edmonton' },
    { en: 'Ottawa', pt: 'Ottawa' },
    { en: 'Winnipeg', pt: 'Winnipeg' },
    { en: 'Quebec City', pt: 'Cidade de Quebec' },
    { en: 'Hamilton', pt: 'Hamilton' },
    { en: 'Victoria', pt: 'Victoria' },
  ],
  PT: [
    { en: 'Lisbon', pt: 'Lisboa' },
    { en: 'Porto', pt: 'Porto' },
    { en: 'Braga', pt: 'Braga' },
    { en: 'Coimbra', pt: 'Coimbra' },
    { en: 'Faro', pt: 'Faro' },
    { en: 'Funchal', pt: 'Funchal' },
    { en: 'Aveiro', pt: 'Aveiro' },
    { en: 'Évora', pt: 'Évora' },
  ],
  ES: [
    { en: 'Madrid', pt: 'Madri' },
    { en: 'Barcelona', pt: 'Barcelona' },
    { en: 'Valencia', pt: 'Valência' },
    { en: 'Seville', pt: 'Sevilha' },
    { en: 'Bilbao', pt: 'Bilbao' },
    { en: 'Málaga', pt: 'Málaga' },
    { en: 'Granada', pt: 'Granada' },
  ],
  FR: [
    { en: 'Paris', pt: 'Paris' },
    { en: 'Marseille', pt: 'Marselha' },
    { en: 'Lyon', pt: 'Lyon' },
    { en: 'Toulouse', pt: 'Toulouse' },
    { en: 'Nice', pt: 'Nice' },
    { en: 'Bordeaux', pt: 'Bordeaux' },
    { en: 'Strasbourg', pt: 'Estrasburgo' },
    { en: 'Nantes', pt: 'Nantes' },
  ],
  DE: [
    { en: 'Berlin', pt: 'Berlim' },
    { en: 'Munich', pt: 'Munique' },
    { en: 'Hamburg', pt: 'Hamburgo' },
    { en: 'Frankfurt', pt: 'Frankfurt' },
    { en: 'Cologne', pt: 'Colônia' },
    { en: 'Stuttgart', pt: 'Stuttgart' },
    { en: 'Düsseldorf', pt: 'Düsseldorf' },
    { en: 'Dresden', pt: 'Dresden' },
  ],
  IT: [
    { en: 'Rome', pt: 'Roma' },
    { en: 'Milan', pt: 'Milão' },
    { en: 'Naples', pt: 'Nápoles' },
    { en: 'Turin', pt: 'Turim' },
    { en: 'Florence', pt: 'Florença' },
    { en: 'Venice', pt: 'Veneza' },
    { en: 'Bologna', pt: 'Bolonha' },
    { en: 'Genoa', pt: 'Gênova' },
  ],
  AR: [
    { en: 'Buenos Aires', pt: 'Buenos Aires' },
    { en: 'Córdoba', pt: 'Córdoba' },
    { en: 'Rosario', pt: 'Rosário' },
    { en: 'Mendoza', pt: 'Mendoza' },
    { en: 'Mar del Plata', pt: 'Mar del Plata' },
    { en: 'La Plata', pt: 'La Plata' },
  ],
  CL: [
    { en: 'Santiago', pt: 'Santiago' },
    { en: 'Valparaíso', pt: 'Valparaíso' },
    { en: 'Concepción', pt: 'Concepción' },
    { en: 'Viña del Mar', pt: 'Viña del Mar' },
  ],
  MX: [
    { en: 'Mexico City', pt: 'Cidade do México' },
    { en: 'Guadalajara', pt: 'Guadalajara' },
    { en: 'Monterrey', pt: 'Monterrey' },
    { en: 'Puebla', pt: 'Puebla' },
    { en: 'Cancún', pt: 'Cancún' },
    { en: 'Tijuana', pt: 'Tijuana' },
  ],
  AU: [
    { en: 'Sydney', pt: 'Sydney' },
    { en: 'Melbourne', pt: 'Melbourne' },
    { en: 'Brisbane', pt: 'Brisbane' },
    { en: 'Perth', pt: 'Perth' },
    { en: 'Adelaide', pt: 'Adelaide' },
    { en: 'Gold Coast', pt: 'Gold Coast' },
    { en: 'Canberra', pt: 'Canberra' },
  ],
  JP: [
    { en: 'Tokyo', pt: 'Tóquio' },
    { en: 'Osaka', pt: 'Osaka' },
    { en: 'Kyoto', pt: 'Quioto' },
    { en: 'Yokohama', pt: 'Yokohama' },
    { en: 'Nagoya', pt: 'Nagoya' },
    { en: 'Sapporo', pt: 'Sapporo' },
    { en: 'Fukuoka', pt: 'Fukuoka' },
  ],
  CN: [
    { en: 'Beijing', pt: 'Pequim' },
    { en: 'Shanghai', pt: 'Xangai' },
    { en: 'Guangzhou', pt: 'Cantão' },
    { en: 'Shenzhen', pt: 'Shenzhen' },
    { en: 'Hong Kong', pt: 'Hong Kong' },
    { en: 'Chengdu', pt: 'Chengdu' },
  ],
};

export function getCitiesForCountry(countryCode: string): { en: string; pt: string }[] {
  return citiesByCountry[countryCode] || [];
}
