export const languages = [
  { code: 'pt', en: 'Portuguese', pt: 'Português' },
  { code: 'en', en: 'English', pt: 'Inglês' },
  { code: 'es', en: 'Spanish', pt: 'Espanhol' },
  { code: 'fr', en: 'French', pt: 'Francês' },
  { code: 'de', en: 'German', pt: 'Alemão' },
  { code: 'it', en: 'Italian', pt: 'Italiano' },
  { code: 'zh', en: 'Chinese (Mandarin)', pt: 'Chinês (Mandarim)' },
  { code: 'ja', en: 'Japanese', pt: 'Japonês' },
  { code: 'ko', en: 'Korean', pt: 'Coreano' },
  { code: 'ar', en: 'Arabic', pt: 'Árabe' },
  { code: 'ru', en: 'Russian', pt: 'Russo' },
  { code: 'hi', en: 'Hindi', pt: 'Hindi' },
  { code: 'he', en: 'Hebrew', pt: 'Hebraico' },
  { code: 'nl', en: 'Dutch', pt: 'Holandês' },
  { code: 'pl', en: 'Polish', pt: 'Polonês' },
  { code: 'tr', en: 'Turkish', pt: 'Turco' },
  { code: 'sv', en: 'Swedish', pt: 'Sueco' },
  { code: 'no', en: 'Norwegian', pt: 'Norueguês' },
  { code: 'da', en: 'Danish', pt: 'Dinamarquês' },
  { code: 'fi', en: 'Finnish', pt: 'Finlandês' },
  { code: 'el', en: 'Greek', pt: 'Grego' },
  { code: 'cs', en: 'Czech', pt: 'Tcheco' },
  { code: 'hu', en: 'Hungarian', pt: 'Húngaro' },
  { code: 'ro', en: 'Romanian', pt: 'Romeno' },
  { code: 'uk', en: 'Ukrainian', pt: 'Ucraniano' },
  { code: 'th', en: 'Thai', pt: 'Tailandês' },
  { code: 'vi', en: 'Vietnamese', pt: 'Vietnamita' },
  { code: 'id', en: 'Indonesian', pt: 'Indonésio' },
  { code: 'ms', en: 'Malay', pt: 'Malaio' },
  { code: 'tl', en: 'Tagalog', pt: 'Tagalo' },
  { code: 'sw', en: 'Swahili', pt: 'Suaíli' },
  { code: 'af', en: 'Afrikaans', pt: 'Africâner' },
  { code: 'ca', en: 'Catalan', pt: 'Catalão' },
  { code: 'hr', en: 'Croatian', pt: 'Croata' },
  { code: 'sk', en: 'Slovak', pt: 'Eslovaco' },
  { code: 'sl', en: 'Slovenian', pt: 'Esloveno' },
  { code: 'sr', en: 'Serbian', pt: 'Sérvio' },
  { code: 'bg', en: 'Bulgarian', pt: 'Búlgaro' },
  { code: 'et', en: 'Estonian', pt: 'Estoniano' },
  { code: 'lv', en: 'Latvian', pt: 'Letão' },
  { code: 'lt', en: 'Lithuanian', pt: 'Lituano' },
  { code: 'fa', en: 'Persian (Farsi)', pt: 'Persa (Farsi)' },
  { code: 'ur', en: 'Urdu', pt: 'Urdu' },
  { code: 'bn', en: 'Bengali', pt: 'Bengali' },
  { code: 'ta', en: 'Tamil', pt: 'Tâmil' },
  { code: 'te', en: 'Telugu', pt: 'Telugu' },
  { code: 'mr', en: 'Marathi', pt: 'Marata' },
  { code: 'gu', en: 'Gujarati', pt: 'Guzerate' },
  { code: 'pa', en: 'Punjabi', pt: 'Punjabi' },
  { code: 'ml', en: 'Malayalam', pt: 'Malaiala' },
  { code: 'kn', en: 'Kannada', pt: 'Canarês' },
  { code: 'other', en: 'Other', pt: 'Outro' },
];

export type Language = (typeof languages)[number];
