export const nationalities = [
  { code: 'AF', en: 'Afghan', pt: 'Afegão(ã)' },
  { code: 'AL', en: 'Albanian', pt: 'Albanês(a)' },
  { code: 'DZ', en: 'Algerian', pt: 'Argelino(a)' },
  { code: 'AD', en: 'Andorran', pt: 'Andorrano(a)' },
  { code: 'AO', en: 'Angolan', pt: 'Angolano(a)' },
  { code: 'AG', en: 'Antiguan', pt: 'Antiguano(a)' },
  { code: 'AR', en: 'Argentine', pt: 'Argentino(a)' },
  { code: 'AM', en: 'Armenian', pt: 'Armênio(a)' },
  { code: 'AU', en: 'Australian', pt: 'Australiano(a)' },
  { code: 'AT', en: 'Austrian', pt: 'Austríaco(a)' },
  { code: 'AZ', en: 'Azerbaijani', pt: 'Azerbaijano(a)' },
  { code: 'BS', en: 'Bahamian', pt: 'Bahamense' },
  { code: 'BH', en: 'Bahraini', pt: 'Bareinita' },
  { code: 'BD', en: 'Bangladeshi', pt: 'Bangladeshiano(a)' },
  { code: 'BB', en: 'Barbadian', pt: 'Barbadiano(a)' },
  { code: 'BY', en: 'Belarusian', pt: 'Bielorrusso(a)' },
  { code: 'BE', en: 'Belgian', pt: 'Belga' },
  { code: 'BZ', en: 'Belizean', pt: 'Belizenho(a)' },
  { code: 'BJ', en: 'Beninese', pt: 'Beninense' },
  { code: 'BT', en: 'Bhutanese', pt: 'Butanês(a)' },
  { code: 'BO', en: 'Bolivian', pt: 'Boliviano(a)' },
  { code: 'BA', en: 'Bosnian', pt: 'Bósnio(a)' },
  { code: 'BW', en: 'Botswanan', pt: 'Botsuanês(a)' },
  { code: 'BR', en: 'Brazilian', pt: 'Brasileiro(a)' },
  { code: 'BN', en: 'Bruneian', pt: 'Bruneano(a)' },
  { code: 'BG', en: 'Bulgarian', pt: 'Búlgaro(a)' },
  { code: 'BF', en: 'Burkinabe', pt: 'Burquinês(a)' },
  { code: 'BI', en: 'Burundian', pt: 'Burundiano(a)' },
  { code: 'CV', en: 'Cape Verdean', pt: 'Cabo-verdiano(a)' },
  { code: 'KH', en: 'Cambodian', pt: 'Cambojano(a)' },
  { code: 'CM', en: 'Cameroonian', pt: 'Camaronês(a)' },
  { code: 'CA', en: 'Canadian', pt: 'Canadense' },
  { code: 'CF', en: 'Central African', pt: 'Centro-africano(a)' },
  { code: 'TD', en: 'Chadian', pt: 'Chadiano(a)' },
  { code: 'CL', en: 'Chilean', pt: 'Chileno(a)' },
  { code: 'CN', en: 'Chinese', pt: 'Chinês(a)' },
  { code: 'CO', en: 'Colombian', pt: 'Colombiano(a)' },
  { code: 'KM', en: 'Comorian', pt: 'Comorense' },
  { code: 'CG', en: 'Congolese', pt: 'Congolês(a)' },
  { code: 'CR', en: 'Costa Rican', pt: 'Costarriquenho(a)' },
  { code: 'HR', en: 'Croatian', pt: 'Croata' },
  { code: 'CU', en: 'Cuban', pt: 'Cubano(a)' },
  { code: 'CY', en: 'Cypriot', pt: 'Cipriota' },
  { code: 'CZ', en: 'Czech', pt: 'Tcheco(a)' },
  { code: 'DK', en: 'Danish', pt: 'Dinamarquês(a)' },
  { code: 'DJ', en: 'Djiboutian', pt: 'Djiboutiano(a)' },
  { code: 'DM', en: 'Dominica Islander', pt: 'Dominiquense' },
  { code: 'DO', en: 'Dominican (Rep.)', pt: 'Dominicano(a)' },
  { code: 'EC', en: 'Ecuadorian', pt: 'Equatoriano(a)' },
  { code: 'EG', en: 'Egyptian', pt: 'Egípcio(a)' },
  { code: 'SV', en: 'Salvadoran', pt: 'Salvadorenho(a)' },
  { code: 'GQ', en: 'Equatorial Guinean', pt: 'Guinéu-equatoriano(a)' },
  { code: 'ER', en: 'Eritrean', pt: 'Eritreu(eia)' },
  { code: 'EE', en: 'Estonian', pt: 'Estoniano(a)' },
  { code: 'SZ', en: 'Swazi', pt: 'Suazi' },
  { code: 'ET', en: 'Ethiopian', pt: 'Etíope' },
  { code: 'FJ', en: 'Fijian', pt: 'Fijiano(a)' },
  { code: 'FI', en: 'Finnish', pt: 'Finlandês(a)' },
  { code: 'FR', en: 'French', pt: 'Francês(a)' },
  { code: 'GA', en: 'Gabonese', pt: 'Gabonês(a)' },
  { code: 'GM', en: 'Gambian', pt: 'Gambiano(a)' },
  { code: 'GE', en: 'Georgian', pt: 'Georgiano(a)' },
  { code: 'DE', en: 'German', pt: 'Alemão(ã)' },
  { code: 'GH', en: 'Ghanaian', pt: 'Ganês(a)' },
  { code: 'GR', en: 'Greek', pt: 'Grego(a)' },
  { code: 'GD', en: 'Grenadian', pt: 'Granadino(a)' },
  { code: 'GT', en: 'Guatemalan', pt: 'Guatemalteco(a)' },
  { code: 'GN', en: 'Guinean', pt: 'Guineano(a)' },
  { code: 'GW', en: 'Bissau-Guinean', pt: 'Guineense' },
  { code: 'GY', en: 'Guyanese', pt: 'Guianense' },
  { code: 'HT', en: 'Haitian', pt: 'Haitiano(a)' },
  { code: 'HN', en: 'Honduran', pt: 'Hondurenho(a)' },
  { code: 'HU', en: 'Hungarian', pt: 'Húngaro(a)' },
  { code: 'IS', en: 'Icelandic', pt: 'Islandês(a)' },
  { code: 'IN', en: 'Indian', pt: 'Indiano(a)' },
  { code: 'ID', en: 'Indonesian', pt: 'Indonésio(a)' },
  { code: 'IR', en: 'Iranian', pt: 'Iraniano(a)' },
  { code: 'IQ', en: 'Iraqi', pt: 'Iraquiano(a)' },
  { code: 'IE', en: 'Irish', pt: 'Irlandês(a)' },
  { code: 'IL', en: 'Israeli', pt: 'Israelense' },
  { code: 'IT', en: 'Italian', pt: 'Italiano(a)' },
  { code: 'JM', en: 'Jamaican', pt: 'Jamaicano(a)' },
  { code: 'JP', en: 'Japanese', pt: 'Japonês(a)' },
  { code: 'JO', en: 'Jordanian', pt: 'Jordaniano(a)' },
  { code: 'KZ', en: 'Kazakhstani', pt: 'Cazaque' },
  { code: 'KE', en: 'Kenyan', pt: 'Queniano(a)' },
  { code: 'KI', en: 'Kiribati', pt: 'Quiribatiano(a)' },
  { code: 'KP', en: 'North Korean', pt: 'Norte-coreano(a)' },
  { code: 'KR', en: 'South Korean', pt: 'Sul-coreano(a)' },
  { code: 'KW', en: 'Kuwaiti', pt: 'Kuwaitiano(a)' },
  { code: 'KG', en: 'Kyrgyz', pt: 'Quirguiz' },
  { code: 'LA', en: 'Laotian', pt: 'Laosiano(a)' },
  { code: 'LV', en: 'Latvian', pt: 'Letão(ã)' },
  { code: 'LB', en: 'Lebanese', pt: 'Libanês(a)' },
  { code: 'LS', en: 'Basotho', pt: 'Lesotiano(a)' },
  { code: 'LR', en: 'Liberian', pt: 'Liberiano(a)' },
  { code: 'LY', en: 'Libyan', pt: 'Líbio(a)' },
  { code: 'LI', en: 'Liechtensteiner', pt: 'Liechtensteinense' },
  { code: 'LT', en: 'Lithuanian', pt: 'Lituano(a)' },
  { code: 'LU', en: 'Luxembourgish', pt: 'Luxemburguês(a)' },
  { code: 'MG', en: 'Malagasy', pt: 'Malgaxe' },
  { code: 'MW', en: 'Malawian', pt: 'Malauiano(a)' },
  { code: 'MY', en: 'Malaysian', pt: 'Malaio(a)' },
  { code: 'MV', en: 'Maldivian', pt: 'Maldivo(a)' },
  { code: 'ML', en: 'Malian', pt: 'Maliano(a)' },
  { code: 'MT', en: 'Maltese', pt: 'Maltês(a)' },
  { code: 'MH', en: 'Marshallese', pt: 'Marshallino(a)' },
  { code: 'MR', en: 'Mauritanian', pt: 'Mauritano(a)' },
  { code: 'MU', en: 'Mauritian', pt: 'Mauriciano(a)' },
  { code: 'MX', en: 'Mexican', pt: 'Mexicano(a)' },
  { code: 'FM', en: 'Micronesian', pt: 'Micronésio(a)' },
  { code: 'MD', en: 'Moldovan', pt: 'Moldávio(a)' },
  { code: 'MC', en: 'Monegasque', pt: 'Monegasco(a)' },
  { code: 'MN', en: 'Mongolian', pt: 'Mongol' },
  { code: 'ME', en: 'Montenegrin', pt: 'Montenegrino(a)' },
  { code: 'MA', en: 'Moroccan', pt: 'Marroquino(a)' },
  { code: 'MZ', en: 'Mozambican', pt: 'Moçambicano(a)' },
  { code: 'MM', en: 'Burmese', pt: 'Birmanês(a)' },
  { code: 'NA', en: 'Namibian', pt: 'Namibiano(a)' },
  { code: 'NR', en: 'Nauruan', pt: 'Nauruano(a)' },
  { code: 'NP', en: 'Nepali', pt: 'Nepalês(a)' },
  { code: 'NL', en: 'Dutch', pt: 'Holandês(a)' },
  { code: 'NZ', en: 'New Zealander', pt: 'Neozelandês(a)' },
  { code: 'NI', en: 'Nicaraguan', pt: 'Nicaraguense' },
  { code: 'NE', en: 'Nigerien', pt: 'Nigerino(a)' },
  { code: 'NG', en: 'Nigerian', pt: 'Nigeriano(a)' },
  { code: 'MK', en: 'Macedonian', pt: 'Macedônio(a)' },
  { code: 'NO', en: 'Norwegian', pt: 'Norueguês(a)' },
  { code: 'OM', en: 'Omani', pt: 'Omanense' },
  { code: 'PK', en: 'Pakistani', pt: 'Paquistanês(a)' },
  { code: 'PW', en: 'Palauan', pt: 'Palauano(a)' },
  { code: 'PS', en: 'Palestinian', pt: 'Palestino(a)' },
  { code: 'PA', en: 'Panamanian', pt: 'Panamenho(a)' },
  { code: 'PG', en: 'Papua New Guinean', pt: 'Papua-nova-guineense' },
  { code: 'PY', en: 'Paraguayan', pt: 'Paraguaio(a)' },
  { code: 'PE', en: 'Peruvian', pt: 'Peruano(a)' },
  { code: 'PH', en: 'Filipino', pt: 'Filipino(a)' },
  { code: 'PL', en: 'Polish', pt: 'Polonês(a)' },
  { code: 'PT', en: 'Portuguese', pt: 'Português(a)' },
  { code: 'QA', en: 'Qatari', pt: 'Catarense' },
  { code: 'RO', en: 'Romanian', pt: 'Romeno(a)' },
  { code: 'RU', en: 'Russian', pt: 'Russo(a)' },
  { code: 'RW', en: 'Rwandan', pt: 'Ruandês(a)' },
  { code: 'KN', en: 'Kittitian', pt: 'São-cristovense' },
  { code: 'LC', en: 'Saint Lucian', pt: 'Santa-lucense' },
  { code: 'VC', en: 'Vincentian', pt: 'São-vicentino(a)' },
  { code: 'WS', en: 'Samoan', pt: 'Samoano(a)' },
  { code: 'SM', en: 'Sammarinese', pt: 'São-marinense' },
  { code: 'ST', en: 'Sao Tomean', pt: 'São-tomense' },
  { code: 'SA', en: 'Saudi', pt: 'Saudita' },
  { code: 'SN', en: 'Senegalese', pt: 'Senegalês(a)' },
  { code: 'RS', en: 'Serbian', pt: 'Sérvio(a)' },
  { code: 'SC', en: 'Seychellois', pt: 'Seichelense' },
  { code: 'SL', en: 'Sierra Leonean', pt: 'Serra-leonês(a)' },
  { code: 'SG', en: 'Singaporean', pt: 'Singapuriano(a)' },
  { code: 'SK', en: 'Slovak', pt: 'Eslovaco(a)' },
  { code: 'SI', en: 'Slovenian', pt: 'Esloveno(a)' },
  { code: 'SB', en: 'Solomon Islander', pt: 'Salomônico(a)' },
  { code: 'SO', en: 'Somali', pt: 'Somali' },
  { code: 'ZA', en: 'South African', pt: 'Sul-africano(a)' },
  { code: 'SS', en: 'South Sudanese', pt: 'Sul-sudanês(a)' },
  { code: 'ES', en: 'Spanish', pt: 'Espanhol(a)' },
  { code: 'LK', en: 'Sri Lankan', pt: 'Cingalês(a)' },
  { code: 'SD', en: 'Sudanese', pt: 'Sudanês(a)' },
  { code: 'SR', en: 'Surinamese', pt: 'Surinamês(a)' },
  { code: 'SE', en: 'Swedish', pt: 'Sueco(a)' },
  { code: 'CH', en: 'Swiss', pt: 'Suíço(a)' },
  { code: 'SY', en: 'Syrian', pt: 'Sírio(a)' },
  { code: 'TW', en: 'Taiwanese', pt: 'Taiwanês(a)' },
  { code: 'TJ', en: 'Tajik', pt: 'Tajique' },
  { code: 'TZ', en: 'Tanzanian', pt: 'Tanzaniano(a)' },
  { code: 'TH', en: 'Thai', pt: 'Tailandês(a)' },
  { code: 'TL', en: 'Timorese', pt: 'Timorense' },
  { code: 'TG', en: 'Togolese', pt: 'Togolês(a)' },
  { code: 'TO', en: 'Tongan', pt: 'Tonganês(a)' },
  { code: 'TT', en: 'Trinidadian', pt: 'Trinitário(a)' },
  { code: 'TN', en: 'Tunisian', pt: 'Tunisiano(a)' },
  { code: 'TR', en: 'Turkish', pt: 'Turco(a)' },
  { code: 'TM', en: 'Turkmen', pt: 'Turcomano(a)' },
  { code: 'TV', en: 'Tuvaluan', pt: 'Tuvaluano(a)' },
  { code: 'UG', en: 'Ugandan', pt: 'Ugandense' },
  { code: 'UA', en: 'Ukrainian', pt: 'Ucraniano(a)' },
  { code: 'AE', en: 'Emirati', pt: 'Emiradense' },
  { code: 'GB', en: 'British', pt: 'Britânico(a)' },
  { code: 'US', en: 'American', pt: 'Americano(a)' },
  { code: 'UY', en: 'Uruguayan', pt: 'Uruguaio(a)' },
  { code: 'UZ', en: 'Uzbek', pt: 'Uzbeque' },
  { code: 'VU', en: 'Vanuatuan', pt: 'Vanuatuense' },
  { code: 'VA', en: 'Vatican', pt: 'Vaticano(a)' },
  { code: 'VE', en: 'Venezuelan', pt: 'Venezuelano(a)' },
  { code: 'VN', en: 'Vietnamese', pt: 'Vietnamita' },
  { code: 'YE', en: 'Yemeni', pt: 'Iemenita' },
  { code: 'ZM', en: 'Zambian', pt: 'Zambiano(a)' },
  { code: 'ZW', en: 'Zimbabwean', pt: 'Zimbabuano(a)' },
];

export type Nationality = (typeof nationalities)[number];
