// Admission gate / approval types

export type EvaluationDecision = 'PENDING' | 'APPROVED' | 'REJECTED';

export type AdmissionGateStatus =
  | 'NOT_STARTED'
  | 'FORM_RECEIVED'
  | 'FORM_APPROVED'
  | 'VISIT_SCHEDULED'
  | 'VISIT_COMPLETED'
  | 'INTERVIEW_COMPLETED'
  | 'VISIT_APPROVED'
  | 'DOCS_REQUESTED'
  | 'DOCS_RECEIVED'
  | 'VIVENCIA_SCHEDULED'
  | 'VIVENCIA_COMPLETED'
  | 'EVALUATION_PENDING'
  | 'EVALUATION_COMPLETED'
  | 'APPROVED'
  | 'ENROLLMENT_PENDING'
  | 'ENROLLMENT_COMPLETED'
  | 'CONTRACT_PENDING'
  | 'CONTRACT_SIGNED'
  | 'FINANCIAL_APPROVED'
  | 'ENROLLED'
  | 'REJECTED';
