-- Add missing AuditAction enum values for contracts, escalations and financial
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_SENT_FOR_SIGNATURE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_LEGAL_APPROVAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_FINANCIAL_APPROVAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_DOCUMENT_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ESCALATION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ESCALATION_RESOLVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FINANCIAL_ANALYSIS_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FINANCIAL_ANALYSIS_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FINANCIAL_ANALYSIS_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_RECORDED';
