import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'pt' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  pt: {
    // Auth
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.register': 'Criar Conta',
    'auth.completeRegistration': 'Complete seu Cadastro',
    'auth.forgotPasswordTitle': 'Recuperar Senha',
    'auth.forgotPasswordDescription': 'Digite seu email para receber instruções de recuperação',
    'auth.sendResetLink': 'Enviar Link de Recuperação',
    'auth.backToLogin': 'Voltar para o Login',
    'auth.emailSent': 'Email Enviado!',
    'auth.checkEmailInstructions': 'Enviamos instruções de recuperação para:',
    'auth.emailNotReceived': 'Não recebeu o email? Verifique sua caixa de spam.',
    'auth.validatingToken': 'Validando link...',
    'auth.invalidToken': 'Link Inválido',
    'auth.tokenExpiredDescription': 'Este link de recuperação é inválido ou expirou. Solicite um novo link.',
    'auth.requestNewLink': 'Solicitar Novo Link',
    'auth.resetPasswordTitle': 'Redefinir Senha',
    'auth.resettingPasswordFor': 'Redefinindo senha para',
    'auth.newPassword': 'Nova Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.resetPassword': 'Redefinir Senha',
    'auth.passwordResetSuccess': 'Senha Redefinida!',
    'auth.passwordResetSuccessDescription': 'Sua senha foi alterada com sucesso. Você já pode fazer login.',
    'auth.goToLogin': 'Ir para o Login',

    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.create': 'Criar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.loading': 'Carregando...',
    'common.noResults': 'Nenhum resultado encontrado',
    'common.confirm': 'Confirmar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.all': 'Todos',
    'common.view': 'Visualizar',
    'common.download': 'Download',
    'common.upload': 'Upload',

    // Modules
    'module.communication': 'Comunicação',
    'module.procurement': 'Compras',
    'module.assets': 'Patrimônio',
    'module.crm': 'CRM',
    'module.ged': 'Documentos',
    'module.admin': 'Admin',
    'module.studentManagement': 'Gestão de Alunos',
    'module.team': 'Gestão de Time',
    'module.pedagogical': 'Pedagógico',
    'module.financial': 'Financeiro',
    'module.crm.description': 'Gestão de leads e admissões',
    'module.studentManagement.description': 'Gestão de alunos matriculados',
    'module.ged.description': 'Gestão eletrônica de documentos',
    'module.admin.description': 'Administração de usuários e sistema',
    'module.communication.description': 'Chat, canais e tickets de suporte',
    'module.team.description': 'Colaboradores, departamentos e estrutura organizacional',
    'module.pedagogical.description': 'Currículo, planos de aula e desempenho acadêmico',
    'module.financial.description': 'Mensalidades, contas a pagar e fluxo de caixa',
    'common.comingSoon': 'Em breve',

    // Navigation
    'nav.launcher': 'Início',
    'nav.profile': 'Meu Perfil',
    'nav.settings': 'Configurações',
    'nav.notifications': 'Notificações',

    // Notifications
    'notifications.title': 'Notificações',
    'notifications.empty': 'Nenhuma notificação',
    'notifications.emptyDescription': 'Você está em dia! Novas notificações aparecerão aqui.',
    'notifications.markAllRead': 'Marcar todas como lidas',
    'notifications.markAsRead': 'Marcar como lida',
    'notifications.delete': 'Excluir',
    'notifications.deleteConfirm': 'Excluir notificação?',
    'notifications.new': 'Nova notificação',
    'notifications.viewAll': 'Ver todas',
    'notifications.justNow': 'Agora mesmo',
    'notifications.unread': 'não lidas',
    'notifications.clearAll': 'Limpar todas',
    'notifications.settings': 'Configurações',
    'notifications.loadMore': 'Carregar mais',
    'notifications.deleteSuccess': 'Notificação excluída',
    'notifications.markedAsRead': 'Marcada como lida',
    'notifications.allMarkedAsRead': 'Todas marcadas como lidas',

    // Communication
    'communication.overview': 'Início',
    'communication.chat': 'Chat',
    'communication.tickets': 'Tickets',
    'communication.tasks': 'Tarefas',
    'communication.calendar': 'Calendário',
    'communication.searchChannels': 'Buscar canais...',
    'communication.channels': 'Canais',
    'communication.directMessages': 'Mensagens Diretas',
    'communication.noConversation': 'Nenhuma conversa',
    'communication.channelStart': 'Início do canal',
    'communication.beFirst': 'Seja o primeiro a enviar uma mensagem!',
    'communication.selectChannel': 'Selecione um canal',
    'communication.selectChannelDesc': 'Escolha um canal para começar a conversar',
    'communication.messageIn': 'Mensagem em',
    'communication.searchTickets': 'Buscar tickets...',
    'communication.allStatus': 'Todos os status',
    'communication.allDepartments': 'Todos os departamentos',
    'communication.noTickets': 'Nenhum ticket encontrado',
    'communication.createFirst': 'Crie um novo ticket para começar',
    'communication.createTicket': 'Criar Ticket',
    'communication.cancel': 'Cancelar',
    'communication.title': 'Título',
    'communication.titlePlaceholder': 'Resumo do problema',
    'communication.department': 'Departamento',
    'communication.selectDepartment': 'Selecione...',
    'communication.priority': 'Prioridade',
    'communication.description': 'Descrição',
    'communication.descriptionPlaceholder': 'Descreva o problema em detalhes...',
    'communication.comments': 'comentários',
    'communication.newChannel': 'Novo Canal',
    'communication.channelName': 'Nome do canal',
    'communication.channelDescription': 'Descrição',
    'communication.channelType': 'Tipo',
    'communication.public': 'Público',
    'communication.private': 'Privado',
    'communication.createChannel': 'Criar Canal',
    'communication.newTicket': 'Novo Ticket',
    'communication.typing': 'está digitando...',
    'communication.loadMore': 'Carregar mensagens anteriores',
    'communication.inDevelopment': 'Em desenvolvimento',
    'communication.ticketDetail': 'Detalhes do Ticket',
    'communication.addComment': 'Adicionar comentário...',
    'communication.sendComment': 'Enviar',
    'communication.status': 'Status',
    'communication.assignee': 'Responsável',
    'communication.creator': 'Criador',
    'communication.createdAt': 'Criado em',
    'communication.activity': 'Atividade',
    'communication.back': 'Voltar',
    'communication.noComments': 'Nenhum comentário ainda',
    'communication.startDM': 'Iniciar Conversa',

    // Departments
    'department.IT': 'TI',
    'department.MAINTENANCE': 'Manutenção',
    'department.CLEANING': 'Limpeza',
    'department.SECRETARIAT': 'Secretaria',
    'department.GENERAL': 'Geral',

    // Tickets
    'ticket.open': 'Aberto',
    'ticket.inProgress': 'Em Andamento',
    'ticket.resolved': 'Resolvido',
    'ticket.closed': 'Fechado',
    'ticket.priority.low': 'Baixa',
    'ticket.priority.medium': 'Média',
    'ticket.priority.high': 'Alta',
    'ticket.priority.urgent': 'Urgente',

    // Procurement
    'procurement.requests': 'Requisições',
    'procurement.newRequest': 'Nova Requisição',
    'procurement.draft': 'Rascunho',
    'procurement.pendingManager': 'Aguardando Gestor',
    'procurement.pendingFinance': 'Aguardando Financeiro',
    'procurement.approved': 'Aprovado',
    'procurement.rejected': 'Rejeitado',
    'procurement.purchased': 'Comprado',

    // Assets
    'assets.inventory': 'Inventário',
    'assets.newAsset': 'Novo Ativo',
    'assets.move': 'Mover',
    'assets.assign': 'Atribuir',
    'assets.available': 'Disponível',
    'assets.inUse': 'Em Uso',
    'assets.maintenance': 'Manutenção',
    'assets.decommissioned': 'Desativado',
    'assets.config': 'Configurações',

    // Resources (unified module)
    'resources.title': 'Gestão de Recursos',
    'resources.dashboard': 'Dashboard',
    'resources.assets': 'Ativos',
    'resources.purchases': 'Compras',
    'resources.maintenance': 'Manutenção',
    'resources.inventory': 'Inventário',
    'resources.suppliers': 'Fornecedores',
    'resources.config': 'Configurações',
    'resources.newAsset': 'Novo Ativo',
    'resources.newPurchase': 'Nova Requisição',
    'resources.newInventory': 'Nova Sessão',
    'resources.totalAssets': 'Total de Ativos',
    'resources.available': 'Disponíveis',
    'resources.inUse': 'Em Uso',
    'resources.inMaintenance': 'Em Manutenção',
    'resources.pendingPurchases': 'Compras Pendentes',
    'resources.totalSpent': 'Total Gasto',
    'resources.alerts': 'Alertas',
    'resources.recentActivity': 'Atividade Recente',
    'resources.upcomingMaintenance': 'Próximas Manutenções',
    'resources.noAlerts': 'Sem alertas no momento',
    'resources.noActivity': 'Nenhuma atividade recente',
    'resources.noMaintenance': 'Nenhuma manutenção agendada',
    'resources.overdueMaintenance': 'manutenção(ões) atrasada(s)',
    'resources.searchAssets': 'Buscar por nome, código ou nº série...',
    'resources.searchPurchases': 'Buscar por título ou código...',
    'resources.allStatuses': 'Todos os status',
    'resources.allCategories': 'Todas categorias',
    'resources.allLocations': 'Todas localizações',
    'resources.noAssets': 'Nenhum ativo encontrado',
    'resources.noAssetsDesc': 'Cadastre ativos para começar',
    'resources.noPurchases': 'Nenhuma requisição',
    'resources.noPurchasesDesc': 'Crie uma nova requisição de compra',
    'resources.noInventory': 'Nenhum inventário',
    'resources.noInventoryDesc': 'Crie uma sessão de inventário para começar',
    'resources.noOverdue': 'Nenhuma manutenção atrasada',
    'resources.noScheduled': 'Nenhuma manutenção agendada nos próximos 30 dias',
    'resources.inventoryProgress': 'Progresso',
    'resources.found': 'encontrados',
    'resources.notFound': 'não encontrados',
    'resources.pending': 'pendentes',
    'resources.startInventory': 'Iniciar Inventário',
    'resources.completeInventory': 'Finalizar Inventário',
    'resources.module.description': 'Compras, patrimônio, manutenção e inventário',
    'resources.subtitle': 'Compras, patrimônio e inventário',
    'resources.new': 'Novo',
    'resources.newSession': 'Nova Sessão',
    'resources.scheduledMaintenance': 'Manutenções Agendadas',
    'resources.noScheduledMaintenance': 'Nenhuma manutenção agendada nos próximos 30 dias',
    'resources.overdue': 'Atrasada',
    'resources.noAssetsFound': 'Nenhum ativo encontrado',
    'resources.noAssetsHint': 'Cadastre ativos para começar',
    'resources.noPurchasesHint': 'Crie uma nova requisição de compra',
    'resources.noInventoryHint': 'Crie uma sessão de inventário para começar',
    'resources.inventorySessions': 'Sessões de Inventário',
    'resources.progress': 'Progresso',
    'resources.selectAssetForMaintenance': 'Selecione um ativo para agendar manutenção',
    'resources.startedBy': 'Iniciado por',
    'resources.vendor': 'Fornecedor',
    'resources.viewAll': 'Ver todos',
    'resources.viewAllPurchases': 'Ver todas as requisições',
    'resources.high': 'Alta',
    'resources.urgent': 'Urgente',

    // CRM
    'crm.leads': 'Leads',
    'crm.newLead': 'Novo Lead',
    'crm.pipeline': 'Pipeline',
    'crm.status.newLead': 'Novo Lead',
    'crm.status.contacted': 'Contactado',
    'crm.status.visitScheduled': 'Visita Agendada',
    'crm.status.enrolled': 'Matriculado',

    // Admin
    'admin.users': 'Usuários',
    'admin.pending': 'Pendentes',
    'admin.archived': 'Arquivados',
    'admin.auditLog': 'Logs de Auditoria',
    'admin.systemSettings': 'Configurações do Sistema',
    'admin.inviteUser': 'Convidar Usuário',
  },
  en: {
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.register': 'Create Account',
    'auth.completeRegistration': 'Complete Your Registration',
    'auth.forgotPasswordTitle': 'Recover Password',
    'auth.forgotPasswordDescription': 'Enter your email to receive recovery instructions',
    'auth.sendResetLink': 'Send Recovery Link',
    'auth.backToLogin': 'Back to Login',
    'auth.emailSent': 'Email Sent!',
    'auth.checkEmailInstructions': 'We sent recovery instructions to:',
    'auth.emailNotReceived': 'Didn\'t receive the email? Check your spam folder.',
    'auth.validatingToken': 'Validating link...',
    'auth.invalidToken': 'Invalid Link',
    'auth.tokenExpiredDescription': 'This recovery link is invalid or expired. Request a new link.',
    'auth.requestNewLink': 'Request New Link',
    'auth.resetPasswordTitle': 'Reset Password',
    'auth.resettingPasswordFor': 'Resetting password for',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.resetPassword': 'Reset Password',
    'auth.passwordResetSuccess': 'Password Reset!',
    'auth.passwordResetSuccessDescription': 'Your password was changed successfully. You can now login.',
    'auth.goToLogin': 'Go to Login',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.noResults': 'No results found',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.all': 'All',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',

    // Modules
    'module.communication': 'Communication',
    'module.procurement': 'Procurement',
    'module.assets': 'Assets',
    'module.crm': 'CRM',
    'module.ged': 'Documents',
    'module.admin': 'Admin',
    'module.studentManagement': 'Student Management',
    'module.team': 'Team Management',
    'module.pedagogical': 'Academics',
    'module.financial': 'Finance',
    'module.crm.description': 'Lead and admissions management',
    'module.studentManagement.description': 'Enrolled student management',
    'module.ged.description': 'Electronic document management',
    'module.admin.description': 'User and system administration',
    'module.communication.description': 'Chat, channels and support tickets',
    'module.team.description': 'Staff, departments and organizational structure',
    'module.pedagogical.description': 'Curriculum, lesson plans and academic performance',
    'module.financial.description': 'Tuition, accounts payable and cash flow',
    'common.comingSoon': 'Coming soon',

    // Navigation
    'nav.launcher': 'Home',
    'nav.profile': 'My Profile',
    'nav.settings': 'Settings',
    'nav.notifications': 'Notifications',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.emptyDescription': 'You\'re all caught up! New notifications will appear here.',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAsRead': 'Mark as read',
    'notifications.delete': 'Delete',
    'notifications.deleteConfirm': 'Delete notification?',
    'notifications.new': 'New notification',
    'notifications.viewAll': 'View all',
    'notifications.justNow': 'Just now',
    'notifications.unread': 'unread',
    'notifications.clearAll': 'Clear all',
    'notifications.settings': 'Settings',
    'notifications.loadMore': 'Load more',
    'notifications.deleteSuccess': 'Notification deleted',
    'notifications.markedAsRead': 'Marked as read',
    'notifications.allMarkedAsRead': 'All marked as read',

    // Communication
    'communication.overview': 'Overview',
    'communication.chat': 'Chat',
    'communication.tickets': 'Tickets',
    'communication.tasks': 'Tasks',
    'communication.calendar': 'Calendar',
    'communication.searchChannels': 'Search channels...',
    'communication.channels': 'Channels',
    'communication.directMessages': 'Direct Messages',
    'communication.noConversation': 'No conversations',
    'communication.channelStart': 'Channel start',
    'communication.beFirst': 'Be the first to send a message!',
    'communication.selectChannel': 'Select a channel',
    'communication.selectChannelDesc': 'Choose a channel to start chatting',
    'communication.messageIn': 'Message in',
    'communication.searchTickets': 'Search tickets...',
    'communication.allStatus': 'All statuses',
    'communication.allDepartments': 'All departments',
    'communication.noTickets': 'No tickets found',
    'communication.createFirst': 'Create a new ticket to get started',
    'communication.createTicket': 'Create Ticket',
    'communication.cancel': 'Cancel',
    'communication.title': 'Title',
    'communication.titlePlaceholder': 'Problem summary',
    'communication.department': 'Department',
    'communication.selectDepartment': 'Select...',
    'communication.priority': 'Priority',
    'communication.description': 'Description',
    'communication.descriptionPlaceholder': 'Describe the problem in detail...',
    'communication.comments': 'comments',
    'communication.newChannel': 'New Channel',
    'communication.channelName': 'Channel name',
    'communication.channelDescription': 'Description',
    'communication.channelType': 'Type',
    'communication.public': 'Public',
    'communication.private': 'Private',
    'communication.createChannel': 'Create Channel',
    'communication.newTicket': 'New Ticket',
    'communication.typing': 'is typing...',
    'communication.loadMore': 'Load earlier messages',
    'communication.inDevelopment': 'In development',
    'communication.ticketDetail': 'Ticket Details',
    'communication.addComment': 'Add a comment...',
    'communication.sendComment': 'Send',
    'communication.status': 'Status',
    'communication.assignee': 'Assignee',
    'communication.creator': 'Creator',
    'communication.createdAt': 'Created at',
    'communication.activity': 'Activity',
    'communication.back': 'Back',
    'communication.noComments': 'No comments yet',
    'communication.startDM': 'Start Conversation',

    // Departments
    'department.IT': 'IT',
    'department.MAINTENANCE': 'Maintenance',
    'department.CLEANING': 'Cleaning',
    'department.SECRETARIAT': 'Secretariat',
    'department.GENERAL': 'General',

    // Tickets
    'ticket.open': 'Open',
    'ticket.inProgress': 'In Progress',
    'ticket.resolved': 'Resolved',
    'ticket.closed': 'Closed',
    'ticket.priority.low': 'Low',
    'ticket.priority.medium': 'Medium',
    'ticket.priority.high': 'High',
    'ticket.priority.urgent': 'Urgent',

    // Procurement
    'procurement.requests': 'Requests',
    'procurement.newRequest': 'New Request',
    'procurement.draft': 'Draft',
    'procurement.pendingManager': 'Pending Manager',
    'procurement.pendingFinance': 'Pending Finance',
    'procurement.approved': 'Approved',
    'procurement.rejected': 'Rejected',
    'procurement.purchased': 'Purchased',

    // Assets
    'assets.inventory': 'Inventory',
    'assets.newAsset': 'New Asset',
    'assets.move': 'Move',
    'assets.assign': 'Assign',
    'assets.available': 'Available',
    'assets.inUse': 'In Use',
    'assets.maintenance': 'Maintenance',
    'assets.decommissioned': 'Decommissioned',
    'assets.config': 'Settings',

    // Resources (unified module)
    'resources.title': 'Resource Management',
    'resources.dashboard': 'Dashboard',
    'resources.assets': 'Assets',
    'resources.purchases': 'Purchases',
    'resources.maintenance': 'Maintenance',
    'resources.inventory': 'Inventory',
    'resources.suppliers': 'Suppliers',
    'resources.config': 'Settings',
    'resources.newAsset': 'New Asset',
    'resources.newPurchase': 'New Request',
    'resources.newInventory': 'New Session',
    'resources.totalAssets': 'Total Assets',
    'resources.available': 'Available',
    'resources.inUse': 'In Use',
    'resources.inMaintenance': 'In Maintenance',
    'resources.pendingPurchases': 'Pending Purchases',
    'resources.totalSpent': 'Total Spent',
    'resources.alerts': 'Alerts',
    'resources.recentActivity': 'Recent Activity',
    'resources.upcomingMaintenance': 'Upcoming Maintenance',
    'resources.noAlerts': 'No alerts at the moment',
    'resources.noActivity': 'No recent activity',
    'resources.noMaintenance': 'No scheduled maintenance',
    'resources.overdueMaintenance': 'overdue maintenance',
    'resources.searchAssets': 'Search by name, code or serial number...',
    'resources.searchPurchases': 'Search by title or code...',
    'resources.allStatuses': 'All statuses',
    'resources.allCategories': 'All categories',
    'resources.allLocations': 'All locations',
    'resources.noAssets': 'No assets found',
    'resources.noAssetsDesc': 'Register assets to get started',
    'resources.noPurchases': 'No requests',
    'resources.noPurchasesDesc': 'Create a new purchase request',
    'resources.noInventory': 'No inventory sessions',
    'resources.noInventoryDesc': 'Create an inventory session to get started',
    'resources.noOverdue': 'No overdue maintenance',
    'resources.noScheduled': 'No scheduled maintenance in the next 30 days',
    'resources.inventoryProgress': 'Progress',
    'resources.found': 'found',
    'resources.notFound': 'not found',
    'resources.pending': 'pending',
    'resources.startInventory': 'Start Inventory',
    'resources.completeInventory': 'Complete Inventory',
    'resources.module.description': 'Purchases, assets, maintenance and inventory',
    'resources.subtitle': 'Purchases, assets and inventory',
    'resources.new': 'New',
    'resources.newSession': 'New Session',
    'resources.scheduledMaintenance': 'Scheduled Maintenance',
    'resources.noScheduledMaintenance': 'No scheduled maintenance in the next 30 days',
    'resources.overdue': 'Overdue',
    'resources.noAssetsFound': 'No assets found',
    'resources.noAssetsHint': 'Register assets to get started',
    'resources.noPurchasesHint': 'Create a new purchase request',
    'resources.noInventoryHint': 'Create an inventory session to get started',
    'resources.inventorySessions': 'Inventory Sessions',
    'resources.progress': 'Progress',
    'resources.selectAssetForMaintenance': 'Select an asset to schedule maintenance',
    'resources.startedBy': 'Started by',
    'resources.vendor': 'Vendor',
    'resources.viewAll': 'View all',
    'resources.viewAllPurchases': 'View all requests',
    'resources.high': 'High',
    'resources.urgent': 'Urgent',

    // CRM
    'crm.leads': 'Leads',
    'crm.newLead': 'New Lead',
    'crm.pipeline': 'Pipeline',
    'crm.status.newLead': 'New Lead',
    'crm.status.contacted': 'Contacted',
    'crm.status.visitScheduled': 'Visit Scheduled',
    'crm.status.enrolled': 'Enrolled',

    // Admin
    'admin.users': 'Users',
    'admin.pending': 'Pending',
    'admin.archived': 'Archived',
    'admin.auditLog': 'Audit Log',
    'admin.systemSettings': 'System Settings',
    'admin.inviteUser': 'Invite User',
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'pt',

      setLanguage: (language: Language) => {
        set({ language });
      },

      t: (key: string) => {
        const { language } = get();
        return translations[language][key] || key;
      },
    }),
    {
      name: 'school-lab-language',
    }
  )
);
