import { AdmissionGateStatus } from '@prisma/client';

// Valid state transitions — expanded with all 21 states
export const validTransitions: Record<AdmissionGateStatus, AdmissionGateStatus[]> = {
  NOT_STARTED: ['FORM_RECEIVED', 'VISIT_SCHEDULED'], // backward compat: NOT_STARTED → VISIT_SCHEDULED still valid
  FORM_RECEIVED: ['FORM_APPROVED', 'REJECTED'],
  FORM_APPROVED: ['VISIT_SCHEDULED'],
  VISIT_SCHEDULED: ['VISIT_COMPLETED', 'NOT_STARTED'], // cancelled → back to NOT_STARTED
  VISIT_COMPLETED: ['INTERVIEW_COMPLETED', 'VISIT_APPROVED', 'REJECTED'], // VISIT_COMPLETED → VISIT_APPROVED still valid for backward compat
  INTERVIEW_COMPLETED: ['VISIT_APPROVED', 'REJECTED'],
  VISIT_APPROVED: ['DOCS_REQUESTED', 'VIVENCIA_SCHEDULED'], // backward compat: VISIT_APPROVED → VIVENCIA_SCHEDULED
  DOCS_REQUESTED: ['DOCS_RECEIVED'],
  DOCS_RECEIVED: ['VIVENCIA_SCHEDULED'],
  VIVENCIA_SCHEDULED: ['VIVENCIA_COMPLETED', 'VISIT_APPROVED'], // cancelled → back to VISIT_APPROVED
  VIVENCIA_COMPLETED: ['EVALUATION_PENDING'],
  EVALUATION_PENDING: ['EVALUATION_COMPLETED'],
  EVALUATION_COMPLETED: ['APPROVED', 'REJECTED'],
  APPROVED: ['ENROLLMENT_PENDING'],
  ENROLLMENT_PENDING: ['ENROLLMENT_COMPLETED'],
  ENROLLMENT_COMPLETED: ['CONTRACT_PENDING'],
  CONTRACT_PENDING: ['CONTRACT_SIGNED', 'REJECTED'],
  CONTRACT_SIGNED: ['FINANCIAL_APPROVED', 'REJECTED'],
  FINANCIAL_APPROVED: ['ENROLLED'],
  ENROLLED: [],
  REJECTED: ['NOT_STARTED'], // Allow recovery: admin can restart the process
};

// Map gate statuses to kanban column slugs for automatic synchronization
export const gateToColumnSlug: Partial<Record<AdmissionGateStatus, string>> = {
  FORM_RECEIVED: 'FORM_RECEIVED',
  FORM_APPROVED: 'FORM_RECEIVED',
  VISIT_SCHEDULED: 'VISIT_SCHEDULED',
  VISIT_COMPLETED: 'VISIT_SCHEDULED',
  INTERVIEW_COMPLETED: 'UNDER_ANALYSIS',
  VISIT_APPROVED: 'UNDER_ANALYSIS',
  DOCS_REQUESTED: 'UNDER_ANALYSIS',
  DOCS_RECEIVED: 'UNDER_ANALYSIS',
  VIVENCIA_SCHEDULED: 'VIVENCIA',
  VIVENCIA_COMPLETED: 'VIVENCIA',
  EVALUATION_PENDING: 'VIVENCIA',
  EVALUATION_COMPLETED: 'VIVENCIA',
  APPROVED: 'APPROVED',
  ENROLLMENT_PENDING: 'APPROVED',
  ENROLLMENT_COMPLETED: 'APPROVED',
  CONTRACT_PENDING: 'APPROVED',
  CONTRACT_SIGNED: 'APPROVED',
  FINANCIAL_APPROVED: 'APPROVED',
  ENROLLED: 'ENROLLED',
  REJECTED: 'REJECTED',
};

export function canTransition(from: AdmissionGateStatus, to: AdmissionGateStatus): boolean {
  return validTransitions[from]?.includes(to) ?? false;
}
